version: '3.6'

services:
  postgresql:
    image: postgres:11.4
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      TZ: CET

  adminer:
    image: adminer
    ports:
    - "8081:8080"

  consul:
    image: consul
    ports:
    - "8300:8300"
    - "8500:8500"
    - "8600:8600"

  rabbitmq:
    image: rabbitmq:management
    ports:
    - "5672:5672"
    - "15672:15672"