version: '3.6'

services:
  postgresql:
    image: postgres:11.4
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ordering"
      TZ: CET

  adminer:
    image: adminer
    ports:
    - "8081:8080"